"""Shared pytest fixtures for integration/regression coverage.

Owned by test-writer. Everything here is either:
  - a writable per-test copy of the committed regression fixture db
    (tests/fixtures/cfb_regression.sqlite3), or
  - a small helper for loading the real cached raw-JSON game sample
    (tests/fixtures/raw_games_sample.json).

Neither ever touches the live `data/cfb.sqlite3` build artifact and neither
makes a live CFBD API call. Both committed fixture dbs
(`cfb_regression.sqlite3`, `nfl_regression.sqlite3`) are generated by
`tests/fixtures/build_regression_fixtures.py` (issue #110): the real ingest
path, cache-first with zero live calls, into a fresh current-schema db,
pruned to the fixture seasons, no ratings. Its docstring has the
regeneration command. Three checks cover different staleness:
`tests/test_regression_fixtures_regenerate_identically.py` fails unless each
fixture's rows and schema equal a fresh regeneration from the committed
cache; `tests/test_regression_fixtures_currency.py` runs `cfb doctor`'s
check, which covers the schema and which (season, season_type) batches are
present but not game content; and `StaleDatabaseWarning` is an error in this
suite (pyproject.toml), so a fixture at an old schema fails every test that
opens it.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from cfb_strength.db.connection import get_conn

FIXTURES_DIR = Path(__file__).parent / "fixtures"
REGRESSION_FIXTURE_DB = FIXTURES_DIR / "cfb_regression.sqlite3"
NFL_REGRESSION_FIXTURE_DB = FIXTURES_DIR / "nfl_regression.sqlite3"
RAW_GAMES_SAMPLE = FIXTURES_DIR / "raw_games_sample.json"


@pytest.fixture
def regression_db(tmp_path: Path) -> Path:
    """A writable per-test copy of the committed CFB fixture db: seasons
    2001, 2003, 2004, 2005, 2013, 2017 and 2019 (the PRD's seven golden
    years), sport='cfb' only. It holds teams (with mascots), team_season,
    games and ingestion_log rows and no precomputed `ratings`, so any test
    using this fixture must run the real rating computation itself rather
    than reading a canned answer."""
    dest = tmp_path / "cfb_regression.sqlite3"
    shutil.copy(REGRESSION_FIXTURE_DB, dest)
    return dest


@pytest.fixture
def regression_conn(regression_db: Path):
    conn = get_conn(regression_db)
    try:
        yield conn
    finally:
        conn.close()


@pytest.fixture
def nfl_regression_db(tmp_path: Path) -> Path:
    """A writable per-test copy of the committed NFL golden-dataset fixture
    db (1999/2004/2013/2022, sport='nfl' only) -- teams/team_season/games/
    ingestion_log, same shape as `regression_db`'s CFB fixture, no
    precomputed `ratings` rows. Generated by
    tests/fixtures/build_regression_fixtures.py from real nflverse data via
    `ingest.nflverse.ingest_season`, cache-first, no live fetch."""
    dest = tmp_path / "nfl_regression.sqlite3"
    shutil.copy(NFL_REGRESSION_FIXTURE_DB, dest)
    return dest


@pytest.fixture
def nfl_regression_conn(nfl_regression_db: Path):
    conn = get_conn(nfl_regression_db)
    try:
        yield conn
    finally:
        conn.close()


@pytest.fixture
def empty_schema_db(tmp_path: Path) -> Path:
    """A fresh sqlite db with the real schema.sql applied, no rows at all --
    for ingest-integration tests that write from scratch."""
    from cfb_strength.db.connection import ensure_schema

    dest = tmp_path / "empty.sqlite3"
    conn = get_conn(dest)
    ensure_schema(conn)
    conn.close()
    return dest
